name: "Neptun ProW+WiFi Local Bridge (Home Assistant add-on)"
version: "0.1.76"
slug: neptun-bridge
description: "Neptun ProW+WiFi Local Bridge (Home Assistant add-on)"
url: "https://github.com/dima11235/ha-neptun-addon"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
host_network: true
ingress: false
init: false
uart: false
tmpfs: false
map:
  - config:rw
  - share:rw
options:
  mqtt:
    listen_port: 2883
    allow_anonymous: true
    user: ""
    password: ""
  ha_mqtt:
    host: "core-mosquitto"
    port: 1883
    user: "!secret mqtt_username"
    password: "!secret mqtt_password"
  bridge:
    cloud_prefix: ""
    topic_prefix: "neptun"
    discovery_prefix: "homeassistant"
    retain: true
    debug: false
schema:
  mqtt:
    listen_port: int
    allow_anonymous: bool
    user: str
    password: str
  ha_mqtt:
    host: str
    port: int
    user: str
    password: str
  bridge:
    cloud_prefix: str
    topic_prefix: str
    discovery_prefix: str
    retain: bool
    debug: bool
 
